# Generated by Django 4.2.7 on 2025-09-25 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctors', '0001_initial'),
        ('patients', '0001_initial'),
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_type', models.CharField(choices=[('consultation', 'Consulta'), ('diagnosis', 'Diagnóstico'), ('treatment', 'Tratamiento'), ('lab_result', 'Resultado de Laboratorio'), ('imaging', 'Imagenología'), ('prescription', 'Receta'), ('vaccination', 'Vacunación'), ('surgery', 'Cirugía'), ('emergency', 'Emergencia')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('diagnosis', models.TextField(blank=True, null=True)),
                ('treatment', models.TextField(blank=True, null=True)),
                ('medications', models.TextField(blank=True, null=True)),
                ('vital_signs', models.JSONField(blank=True, help_text='Signos vitales en formato JSON', null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('is_confidential', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medical_records', to='appointments.appointment')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_records', to='doctors.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_records', to='patients.patient')),
            ],
            options={
                'verbose_name': 'Expediente Clínico',
                'verbose_name_plural': 'Expedientes Clínicos',
                'db_table': 'medical_records',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medication_name', models.CharField(max_length=200)),
                ('dosage', models.CharField(max_length=100)),
                ('frequency', models.CharField(max_length=100)),
                ('duration', models.CharField(max_length=100)),
                ('instructions', models.TextField(blank=True, null=True)),
                ('quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('prescribed_date', models.DateTimeField(auto_now_add=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('medical_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='medical_records.medicalrecord')),
            ],
            options={
                'verbose_name': 'Receta',
                'verbose_name_plural': 'Recetas',
                'db_table': 'prescriptions',
                'ordering': ['-prescribed_date'],
            },
        ),
        migrations.CreateModel(
            name='LabResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(max_length=200)),
                ('test_code', models.CharField(blank=True, max_length=50, null=True)),
                ('result_value', models.CharField(max_length=100)),
                ('normal_range', models.CharField(blank=True, max_length=100, null=True)),
                ('unit', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('completed', 'Completado'), ('abnormal', 'Anormal'), ('critical', 'Crítico')], default='pending', max_length=20)),
                ('lab_name', models.CharField(blank=True, max_length=200, null=True)),
                ('test_date', models.DateTimeField()),
                ('result_date', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('file_attachment', models.FileField(blank=True, null=True, upload_to='lab_results/')),
                ('medical_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_results', to='medical_records.medicalrecord')),
            ],
            options={
                'verbose_name': 'Resultado de Laboratorio',
                'verbose_name_plural': 'Resultados de Laboratorio',
                'db_table': 'lab_results',
                'ordering': ['-test_date'],
            },
        ),
        migrations.CreateModel(
            name='ImagingResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imaging_type', models.CharField(choices=[('xray', 'Radiografía'), ('ct', 'Tomografía Computada'), ('mri', 'Resonancia Magnética'), ('ultrasound', 'Ultrasonido'), ('mammography', 'Mamografía'), ('pet', 'PET Scan'), ('bone_scan', 'Gammagrafía Ósea')], max_length=20)),
                ('body_part', models.CharField(max_length=100)),
                ('findings', models.TextField()),
                ('impression', models.TextField()),
                ('radiologist', models.CharField(blank=True, max_length=200, null=True)),
                ('imaging_date', models.DateTimeField()),
                ('report_date', models.DateTimeField(blank=True, null=True)),
                ('images', models.JSONField(blank=True, help_text='URLs de imágenes en formato JSON', null=True)),
                ('file_attachment', models.FileField(blank=True, null=True, upload_to='imaging_results/')),
                ('medical_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imaging_results', to='medical_records.medicalrecord')),
            ],
            options={
                'verbose_name': 'Resultado de Imagenología',
                'verbose_name_plural': 'Resultados de Imagenología',
                'db_table': 'imaging_results',
                'ordering': ['-imaging_date'],
            },
        ),
    ]
