# Generated by Django 4.2.7 on 2025-09-25 15:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('doctors', '0001_initial'),
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('notification_type', models.CharField(choices=[('appointment_reminder', 'Recordatorio de Cita'), ('appointment_confirmation', 'Confirmación de Cita'), ('appointment_cancellation', 'Cancelación de Cita'), ('lab_result', 'Resultado de Laboratorio'), ('imaging_result', 'Resultado de Imagenología'), ('prescription_ready', 'Receta Lista'), ('queue_update', 'Actualización de Fila'), ('general', 'General'), ('emergency', 'Emergencia')], max_length=30)),
                ('title_template', models.CharField(max_length=200)),
                ('message_template', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Plantilla de Notificación',
                'verbose_name_plural': 'Plantillas de Notificaciones',
                'db_table': 'notification_templates',
            },
        ),
        migrations.CreateModel(
            name='NotificationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_enabled', models.BooleanField(default=True)),
                ('email_appointment_reminders', models.BooleanField(default=True)),
                ('email_lab_results', models.BooleanField(default=True)),
                ('email_imaging_results', models.BooleanField(default=True)),
                ('email_prescriptions', models.BooleanField(default=True)),
                ('sms_enabled', models.BooleanField(default=False)),
                ('sms_appointment_reminders', models.BooleanField(default=False)),
                ('sms_urgent_notifications', models.BooleanField(default=True)),
                ('push_enabled', models.BooleanField(default=True)),
                ('push_appointment_reminders', models.BooleanField(default=True)),
                ('push_queue_updates', models.BooleanField(default=True)),
                ('push_general_notifications', models.BooleanField(default=True)),
                ('reminder_hours_before', models.PositiveIntegerField(default=24, help_text='Horas antes de la cita para enviar recordatorio')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configuración de Notificaciones',
                'verbose_name_plural': 'Configuraciones de Notificaciones',
                'db_table': 'notification_settings',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('appointment_reminder', 'Recordatorio de Cita'), ('appointment_confirmation', 'Confirmación de Cita'), ('appointment_cancellation', 'Cancelación de Cita'), ('lab_result', 'Resultado de Laboratorio'), ('imaging_result', 'Resultado de Imagenología'), ('prescription_ready', 'Receta Lista'), ('queue_update', 'Actualización de Fila'), ('general', 'General'), ('emergency', 'Emergencia')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('priority', models.CharField(choices=[('low', 'Baja'), ('medium', 'Media'), ('high', 'Alta'), ('urgent', 'Urgente')], default='medium', max_length=10)),
                ('is_read', models.BooleanField(default=False)),
                ('is_sent', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='appointments.appointment')),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='doctors.doctor')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='patients.patient')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'db_table': 'notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
