# Generated by Django 4.2.7 on 2025-09-25 15:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patients', '0001_initial'),
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_date', models.DateTimeField()),
                ('duration', models.PositiveIntegerField(default=30, help_text='Duración en minutos')),
                ('status', models.CharField(choices=[('scheduled', 'Programada'), ('confirmed', 'Confirmada'), ('in_progress', 'En Progreso'), ('completed', 'Completada'), ('cancelled', 'Cancelada'), ('no_show', 'No se presentó'), ('rescheduled', 'Reprogramada')], default='scheduled', max_length=20)),
                ('appointment_type', models.CharField(choices=[('consultation', 'Consulta'), ('follow_up', 'Seguimiento'), ('emergency', 'Emergencia'), ('routine', 'Rutina'), ('specialist', 'Especialista')], default='consultation', max_length=20)),
                ('reason', models.TextField(help_text='Motivo de la cita')),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_appointments', to=settings.AUTH_USER_MODEL)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='doctors.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='patients.patient')),
            ],
            options={
                'verbose_name': 'Cita',
                'verbose_name_plural': 'Citas',
                'db_table': 'appointments',
                'ordering': ['-appointment_date'],
            },
        ),
        migrations.CreateModel(
            name='VirtualQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('queue_number', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('waiting', 'En Espera'), ('called', 'Llamado'), ('in_progress', 'En Atención'), ('completed', 'Atendido'), ('cancelled', 'Cancelado')], default='waiting', max_length=20)),
                ('estimated_wait_time', models.PositiveIntegerField(blank=True, help_text='Tiempo estimado en minutos', null=True)),
                ('check_in_time', models.DateTimeField(auto_now_add=True)),
                ('called_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queue_entries', to='doctors.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queue_entries', to='patients.patient')),
            ],
            options={
                'verbose_name': 'Fila Virtual',
                'verbose_name_plural': 'Filas Virtuales',
                'db_table': 'virtual_queue',
                'ordering': ['queue_number'],
            },
        ),
        migrations.CreateModel(
            name='AppointmentReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_type', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('push', 'Push Notification')], max_length=10)),
                ('reminder_time', models.DateTimeField()),
                ('is_sent', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='appointments.appointment')),
            ],
            options={
                'verbose_name': 'Recordatorio de Cita',
                'verbose_name_plural': 'Recordatorios de Citas',
                'db_table': 'appointment_reminders',
            },
        ),
    ]
