name: paciente_360
description: Plataforma integral para gestión de pacientes y hospitales

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # UI y diseño
  cupertino_icons: ^1.0.2
  
  # Estado y navegación
  provider: ^6.1.1
  go_router: ^12.1.3
  
  # HTTP y API
  http: ^1.1.2
  
  # Utilidades
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/