# Generated by Django 4.2.7 on 2025-09-25 15:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_number', models.CharField(max_length=20, unique=True)),
                ('specialty', models.CharField(choices=[('general', 'Medicina General'), ('cardiology', 'Cardiología'), ('dermatology', 'Dermatología'), ('neurology', 'Neurología'), ('orthopedics', 'Ortopedia'), ('pediatrics', 'Pediatría'), ('gynecology', 'Ginecología'), ('psychiatry', 'Psiquiatría'), ('ophthalmology', 'Oftalmología'), ('otolaryngology', 'Otorrinolaringología'), ('urology', 'Urología'), ('oncology', 'Oncología'), ('endocrinology', 'Endocrinología'), ('gastroenterology', 'Gastroenterología'), ('pulmonology', 'Neumología'), ('rheumatology', 'Reumatología'), ('anesthesiology', 'Anestesiología'), ('radiology', 'Radiología'), ('pathology', 'Patología'), ('emergency', 'Medicina de Emergencia')], max_length=50)),
                ('years_experience', models.PositiveIntegerField(default=0)),
                ('education', models.TextField(blank=True, null=True)),
                ('certifications', models.TextField(blank=True, null=True)),
                ('languages', models.CharField(blank=True, help_text='Idiomas separados por comas', max_length=200, null=True)),
                ('consultation_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_available', models.BooleanField(default=True)),
                ('consultation_duration', models.PositiveIntegerField(default=30, help_text='Duración en minutos')),
                ('bio', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Doctor',
                'verbose_name_plural': 'Doctores',
                'db_table': 'doctors',
            },
        ),
        migrations.CreateModel(
            name='DoctorSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='doctors.doctor')),
            ],
            options={
                'verbose_name': 'Horario de Doctor',
                'verbose_name_plural': 'Horarios de Doctores',
                'db_table': 'doctor_schedules',
                'unique_together': {('doctor', 'day_of_week')},
            },
        ),
    ]
